#!/usr/bin/env bash
set -euo pipefail

# Mesa/EGL comes from the host. Bundling an older libwayland alongside it
# causes EGL_BAD_PARAMETER on newer distributions (including Fedora 44).
# Keep WebKit and GTK bundled, but use the host's Wayland client libraries.
# https://github.com/tauri-apps/tauri/issues/15665
appimage=$(realpath "${1:?Usage: fix-appimage.sh path/to/application.AppImage}")
command -v mksquashfs >/dev/null
chmod +x "$appimage"
offset=$("$appimage" --appimage-offset)
[[ "$offset" =~ ^[0-9]+$ ]] && (( offset > 0 ))
workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

(
  cd "$workdir"
  "$appimage" --appimage-extract > /dev/null
)

find "$workdir/squashfs-root/usr/lib" -name 'libwayland-*.so*' -print -delete

# Ensure all files and directories in AppDir are readable and executable
# for any user. Tauri may package AppRun.wrapped with mode 0770, causing
# permission denied when firejail or the AppImage catalog tests run as non-root.
chmod -R a+rX "$workdir/squashfs-root"
if [ -e "$workdir/squashfs-root/AppRun.wrapped" ]; then
  chmod a+rx "$workdir/squashfs-root/AppRun.wrapped"
fi

# Retain the exact unsigned AppImage runtime generated by Tauri and replace
# only its SquashFS payload. No extra runtime download or FUSE mount is needed.
mksquashfs "$workdir/squashfs-root" "$workdir/payload.squashfs" \
  -noappend -all-root -comp gzip -no-progress -processors 2 > /dev/null
head -c "$offset" "$appimage" > "$workdir/fixed.AppImage"
cat "$workdir/payload.squashfs" >> "$workdir/fixed.AppImage"
chmod +x "$workdir/fixed.AppImage"
[[ "$("$workdir/fixed.AppImage" --appimage-offset)" == "$offset" ]]
cp "$workdir/fixed.AppImage" "$appimage"
echo "Repacked $(basename "$appimage") with host Wayland libraries."
